charset: utf-8
company-name: Radancy
company-url: https://radancy.com
defaults:
-
  values:
    layout: "default"
exclude: [
  README.md,
  CNAME,
  _config.yml,
  _template.bat
]
destination: _httpdocs
git-url: https://radancy.dev
highlighter: rouge
lang: en
markdown: kramdown
name: Component Library
owner-name: Michael Spellacy
owner-email: michael.spellacy@radancy.com
owner-image: https://www.gravatar.com/avatar/89e429d4a3effa9601cd19a851c0003e.jpg
permalink: /:title/
port: 4006
repo: https://github.com/radancyco/tb-ajd-template
sass:
  style: :compressed
theme-color: "#6E00EE"
